name: Deploy Engine to EC2 (PROD)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy PROD
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /var/www/xeliai_engine
            git pull origin main
            /var/www/xeliai_engine/venv/bin/pip install -r requirements.txt
            /var/www/xeliai_engine/venv/bin/pip install gunicorn
            sudo systemctl restart xeliai
          EOF